// creat a random generator that spits out the follwoing : the time and date, the action that will take place, the reson why that happened.
const timeArray = ['1:15','1:00','12:00','11:30','6:45','9:12','3:55','5:09','7:30','2:10','10:25','11:58','4:25','6:10','12:25'];
const dateArray = ['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'];
const actionArray =['You will stubb your toe','Win a half marathon','adopt a cat','forget your wallet','poop your pants','find a $100 bill on the ground','have the best meal of your life','accidently get your left sock wet on the way to work'];
